Random sampling of IDs in hash table
renproject/aw pull request #66
Opened 2021-02-17 12:14 UTC by rahulghangas

Add ability to query n random elements from sorted array of IDs

Depending on size of sorted IDs and the number of random elements requested, the function either uses a partial permutation algorithm for sampling or uses Floyd's sampling algorithm

2021-02-17 12:19 UTC, rahulghangas commented
Will need some benchmarking to tweak the parameters, but should be able to do correctness tests and merge it ASAP

2021-02-18 05:18 UTC, jazg requested changes
Looks good! Although it might be good to test the randomisation aspect, e.g. by generating `n` random lists (with sufficiently large elements) and ensuring they're all unique.

2021-02-18 05:20 UTC, rahulghangas commented
Sure, I'll push a test for that in a bit. I'm currently benchmarking with different parameters as well, but I think that can be done as a separate issue after this is merged

2021-02-18 06:11 UTC, jazg approved these changes

2021-02-18 06:12 UTC, merged